export const PUBLIC_API_ENDPOINT = 'https://1vtglwl3-20099.asse.devtunnels.ms'
export const PUBLIC_API_ENDPOINT_AI = 'https://1vtglwl3-5000.asse.devtunnels.ms'
export const PUBLIC_FE_ENDPOINT = 'http://192.168.1.28:8081'
export const PUBLIC_MUSIC_ENDPOINT = 'https://melodies.sgp1.cdn.digitaloceanspaces.com/PBL6/'
export const PUBLIC_KEY_DECODE = '4Uc/8L1zNPg2yNtxdu+jH/mkKpqUjEZz5bEPJjbWS8fOFHnKTMufyIKvryc6Z51V'
export const PUBLIC_API_LYRIC = 'puQc25_RvoFIGEQIv3myeKjTCXL42FXL2T9OPCPJoMJ-SKlkoddHVA1O20qTRNCs'